### PR TITLE
Added Spanish language (es_es.json)

### PR DESCRIPTION
**Pull request by FrannDzs**
Hello, I have added support for the Spanish language. I will soon add templates for language variations. Cheers!

### CODE REVIEW

**Comment by Flanks255** [comment]
Looks good, only question i have is the translation for "Shift" does that say "left shift"?
technically either shift key will work.

**Comment by FrannDzs** [comment]
> Looks good, only question i have is the translation for "Shift" does that say "left shift"?
> technically either shift key will work.

Hello, you are right, I am correcting it now.

**Comment by FrannDzs** [comment]
> Looks good, only question i have is the translation for "Shift" does that say "left shift"?
> technically either shift key will work.

Sorry, it's an abbreviation for left shift. It's fine the way it's written.

**Comment by Flanks255** [comment]
ok, just checking, i dont speak spanish, didnt know if that made sense or not.

**Review by Flanks255 — APPROVED** [review]

**Comment by FrannDzs** [comment]
> ok, just checking, i dont speak spanish, didnt know if that made sense or not.

No problem man! Good night!

**Pull request merged**
