### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by momo-i2**

### CODE REVIEW

**Comment by Flanks255** [comment]
Hey, thanks for translating, something is messed up with the git commits in the PR, and its including all my changes from the last couple days as well as yours. 
image

Perhaps you could recreate the PR? or i could add the ja_jp.json file manually and credit you in the commit?

**Comment by Flanks255** [comment]
Or rebase it? that might fix it as well.

**Comment by momo-i2** [comment]
>Perhaps you could recreate the PR? 

OK, I will recreate the PR, and will close after new PR.

**Comment by momo-i2** [comment]
Recreated on #51

**Pull request closed without merging**
